version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
          - "astro-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      postcss:
        patterns:
          - "postcss*"
          - "cssnano"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
      typescript:
        patterns:
          - "@typescript-eslint/*"
          - "typescript"
          - "typescript-eslint"
